export const environment = {
  API_URL: 'https://date.nager.at/api/v3',
  NUMBER_OF_COUNTRIES_ON_WIDGET: 3,
  PAGINATION_START_YEAR: 2020,
  PAGINATION_END_YEAR: 2030,
  DEFAULT_COUNTRY_HOLIDAYS_YEAR: 2024,
};
